parser: 'babel-eslint'
parserOptions:
  sourceType: 'module'

env:
  es6: true
  node: true
  commonjs: true
  browser: false
  mocha: true

rules:
  linebreak-style: ['error', 'windows']

extends: ['airbnb', 'eslint:recommended']
